### ISSUE TITLE
Limiting Scale

### ISSUE THREAD

**Issue by zleight1** [ZEISS/on-demand-agents#1]
Awesome article and demo, but I had a question about limiting scaling. How would you approach limiting the number of agents that would be alive at any time?

For example someone queues up 30 builds you could be spinning up 30 agents and really bog down a cluster quickly. How would you limit that to 15 at any one time etc.?

I was thinking about having an agent-less step make a rest call to some sort of “agent queuer” (basically do what you’re doing with the init agent but inside a pod). I wasn’t sure if it was the right approach, or even to go the route of some batch job scheduler.

Would be great to hear your thoughts, as were in the middle of this exact project and your article was a great find.

🙏🏼

**Comment by foliba** [comment]
@zleight1 do you really want to prevent s.o. from spinning up more than X agents? A)
Or is your issue about ensuring that the cluster won't be maxed out? B)

If B)
Enabling node auto scaling on the underlying agent cluster would be an approach.

If A)
That's kinda more tricky... Want to limit it globally? Per user? What if pipelines are run by ci/cd and not a human pressing a button?
What exactly is the reason you would want to limit your agent queue size (except for B)?

**Comment by zleight1** [comment]
I guess my initial concern was that we have some heavy windows images and if we suddenly spun up a lot of them it might be an issue. We're in the process of migrating off of windows machines to linux anyway but some frameworks we use still require a pretty heavy agent image.

I'll look into node autoscaling a bit more. Thanks!

**Comment by C123R** [comment]
As already mentioned by @foliba, you can use a cluster auto scaler that would spin up a new node if PODs are in pending(Scheduling state) but tbh it usually takes more than 2-3 minutes to bring up another node in your cluster. Maybe you could use [Virtual Kubelet](https://github.com/virtual-kubelet/virtual-kubelet#how-it-works) with some pod scheduling policies.

If you want to hard limit the number of agents(POD), you can use [Pod Quota for Namespace](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace/).
